//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainCheck) DeepCopyInto(out *DrainCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainCheck.
func (in *DrainCheck) DeepCopy() *DrainCheck {
	if in == nil {
		return nil
	}
	out := new(DrainCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainCheckList) DeepCopyInto(out *DrainCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DrainCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainCheckList.
func (in *DrainCheckList) DeepCopy() *DrainCheckList {
	if in == nil {
		return nil
	}
	out := new(DrainCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainCheckSpec) DeepCopyInto(out *DrainCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainCheckSpec.
func (in *DrainCheckSpec) DeepCopy() *DrainCheckSpec {
	if in == nil {
		return nil
	}
	out := new(DrainCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainCheckStatus) DeepCopyInto(out *DrainCheckStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainCheckStatus.
func (in *DrainCheckStatus) DeepCopy() *DrainCheckStatus {
	if in == nil {
		return nil
	}
	out := new(DrainCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAndName) DeepCopyInto(out *NamespaceAndName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAndName.
func (in *NamespaceAndName) DeepCopy() *NamespaceAndName {
	if in == nil {
		return nil
	}
	out := new(NamespaceAndName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrain) DeepCopyInto(out *NodeDrain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrain.
func (in *NodeDrain) DeepCopy() *NodeDrain {
	if in == nil {
		return nil
	}
	out := new(NodeDrain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDrain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrainList) DeepCopyInto(out *NodeDrainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeDrain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrainList.
func (in *NodeDrainList) DeepCopy() *NodeDrainList {
	if in == nil {
		return nil
	}
	out := new(NodeDrainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDrainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrainSpec) DeepCopyInto(out *NodeDrainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrainSpec.
func (in *NodeDrainSpec) DeepCopy() *NodeDrainSpec {
	if in == nil {
		return nil
	}
	out := new(NodeDrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrainStatus) DeepCopyInto(out *NodeDrainStatus) {
	*out = *in
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
	if in.PodsToBeEvicted != nil {
		in, out := &in.PodsToBeEvicted, &out.PodsToBeEvicted
		*out = make([]NamespaceAndName, len(*in))
		copy(*out, *in)
	}
	if in.PendingEvictionPods != nil {
		in, out := &in.PendingEvictionPods, &out.PendingEvictionPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodsToRestart != nil {
		in, out := &in.PodsToRestart, &out.PodsToRestart
		*out = make([]NamespaceAndName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrainStatus.
func (in *NodeDrainStatus) DeepCopy() *NodeDrainStatus {
	if in == nil {
		return nil
	}
	out := new(NodeDrainStatus)
	in.DeepCopyInto(out)
	return out
}
